// Categories for product filtering based on activities
export const categories = [
  "All",
  "Swimming",
  "Sunbathing",
  "Snorkeling",
  "Scuba Diving",
  "Paddling",
  "Beach Games",
  "Shade & Comfort",
  "Kids",
  "Storage",
  "New Arrivals"
];

// Product catalog data restructured for beach rental items
export const products = [
  {
    id: 1,
    title: "Premium Beach Chair",
    price: "299",
    rentPrice: 49,
    shopName: "BeachComfort",
    images: [
      require("@/assets/Ecom/beach-chair1.png"),
      require("@/assets/Ecom/beach-chair1.png"),
      require("@/assets/Ecom/beach-chair1.png"),
    ],
    description:
      "Comfortable and adjustable beach chair with multiple reclining positions. Features a built-in cup holder and storage pocket. Lightweight aluminum frame makes it easy to carry to your perfect spot on the beach.",
    category: ["Sunbathing", "Shade & Comfort", "New Arrivals"],
    location: "Calangute Beach",
    available: 8,
  },
  {
    id: 2,
    title: "Large Beach Umbrella",
    price: "399",
    rentPrice: 59,
    shopName: "ShadeMakers",
    images: [
      require("@/assets/Ecom/umbrella1.png"),
      require("@/assets/Ecom/umbrella1.png"),
      require("@/assets/Ecom/umbrella1.png"),
    ],
    description:
      "Oversized beach umbrella with UPF 50+ sun protection. The sturdy sand anchor keeps it secure even in windy conditions. Tilt mechanism allows you to adjust for optimal shade throughout the day.",
    category: ["Sunbathing", "Shade & Comfort"],
    location: "Baga Beach",
    available: 5,
  },
  {
    id: 3,
    title: "Pop-up Beach Tent",
    price: "599",
    rentPrice: 99,
    shopName: "BeachShelter",
    images: [
      require("@/assets/Ecom/tent1.png"),
      require("@/assets/Ecom/tent1.png"),
      require("@/assets/Ecom/tent1.png"),
    ],
    description:
      "Easy setup pop-up beach tent that provides instant shade and privacy. Perfect for families with small children or anyone wanting protection from the sun. Features mesh windows for ventilation and sand pockets for stability.",
    category: ["Shade & Comfort", "Kids", "New Arrivals"],
    location: "Palolem Beach",
    available: 3,
  },
  {
    id: 4,
    title: "Sun Lounger",
    price: "499",
    rentPrice: 79,
    shopName: "BeachComfort",
    images: [
      require("@/assets/Ecom/lounger1.png"),
      require("@/assets/Ecom/lounger1.png"),
      require("@/assets/Ecom/lounger1.png"),
    ],
    description:
      "Premium sun lounger with adjustable backrest and built-in wheels for easy transportation. The breathable fabric keeps you cool while the padded headrest ensures maximum comfort during your beach day.",
    category: ["Sunbathing", "Shade & Comfort"],
    location: "Anjuna Beach",
    available: 6,
  },
  {
    id: 5,
    title: "Premium Cooler Box",
    price: "699",
    rentPrice: 89,
    shopName: "BeachEssentials",
    images: [
      require("@/assets/Ecom/cooler1.png"),
      require("@/assets/Ecom/cooler1.png"),
      require("@/assets/Ecom/cooler1.png"),
    ],
    description:
      "High-performance cooler that keeps ice frozen for up to 3 days. Perfect for storing drinks and snacks during your beach day. Features comfortable carrying handles and a drain plug for easy cleaning.",
    category: ["Storage", "New Arrivals"],
    location: "Morjim Beach",
    available: 4,
  },
  {
    id: 6,
    title: "Snorkeling Set",
    price: "799",
    rentPrice: 129,
    shopName: "OceanExplorer",
    images: [
      require("@/assets/Ecom/snorkel1.png"),
      require("@/assets/Ecom/snorkel1.png"),
      require("@/assets/Ecom/snorkel1.png"),
    ],
    description:
      "Complete snorkeling set including mask, snorkel, and fins. The silicone skirt on the mask ensures a watertight seal while the dry-top snorkel prevents water from entering. Adjustable fins provide efficient propulsion for all-day exploration.",
    category: ["Snorkeling", "Swimming"],
    location: "Palolem Beach",
    available: 10,
  },
  {
    id: 7,
    title: "Boogie Board",
    price: "399",
    rentPrice: 69,
    shopName: "WaveRiders",
    images: [
      require("@/assets/Ecom/boogie1.png"),
      require("@/assets/Ecom/boogie1.png"),
      require("@/assets/Ecom/boogie1.png"),
    ],
    description:
      "Lightweight and durable bodyboard perfect for riding waves of all sizes. The slick bottom surface reduces drag while the crescent tail provides excellent maneuverability. Includes a wrist leash to keep the board secure.",
    category: ["Swimming", "Paddling", "Kids"],
    location: "Arambol Beach",
    available: 8,
  },
  {
    id: 8,
    title: "Beginner Surfboard",
    price: "1299",
    rentPrice: 199,
    shopName: "WaveRiders",
    images: [
      require("@/assets/Ecom/surf1.png"),
      require("@/assets/Ecom/surf1.png"),
      require("@/assets/Ecom/surf1.png"),
    ],
    description:
      "Stable and forgiving surfboard designed specifically for beginners. The soft top construction ensures safety while learning, and the generous volume provides excellent flotation. Includes a leash and wax.",
    category: ["Swimming", "Paddling"],
    location: "Ashwem Beach",
    available: 5,
  },
  {
    id: 9,
    title: "Inflatable Kayak",
    price: "1499",
    rentPrice: 249,
    shopName: "PaddlePro",
    images: [
      require("@/assets/Ecom/kayak1.png"),
      require("@/assets/Ecom/kayak1.png"),
      require("@/assets/Ecom/kayak1.png"),
    ],
    description:
      "Two-person inflatable kayak that's perfect for exploring coastal waters. The puncture-resistant material ensures durability while the multiple air chambers provide safety. Includes paddles and a pump for quick setup.",
    category: ["Paddling", "New Arrivals"],
    location: "Mandrem Beach",
    available: 3,
  },
  {
    id: 10,
    title: "Adult Life Jacket",
    price: "599",
    rentPrice: 79,
    shopName: "SafetyFirst",
    images: [
      require("@/assets/Ecom/lifejacket1.png"),
      require("@/assets/Ecom/lifejacket1.png"),
      require("@/assets/Ecom/lifejacket1.png"),
    ],
    description:
      "Coast Guard approved life jacket with adjustable straps for a secure fit. The lightweight design doesn't restrict movement while providing reliable flotation. Multiple sizes available to ensure proper safety for all users.",
    category: ["Swimming", "Paddling", "Safety"],
    location: "Candolim Beach",
    available: 15,
  },
  {
    id: 11,
    title: "Scuba Diving Kit",
    price: "2999",
    rentPrice: 499,
    shopName: "DeepBlue",
    images: [
      require("@/assets/Ecom/scuba1.png"),
      require("@/assets/Ecom/scuba1.png"),
      require("@/assets/Ecom/scuba1.png"),
    ],
    description:
      "Complete scuba diving equipment including BCD, regulator, tank, wetsuit, and fins. All gear is professionally maintained and tested for safety. Rental includes a brief orientation session with our certified instructors.",
    category: ["Scuba Diving", "Swimming"],
    location: "Grande Island",
    available: 6,
  },
  {
    id: 12,
    title: "Water Shoes",
    price: "299",
    rentPrice: 49,
    shopName: "BeachEssentials",
    images: [
      require("@/assets/Ecom/watershoes1.png"),
      require("@/assets/Ecom/watershoes1.png"),
      require("@/assets/Ecom/watershoes1.png"),
    ],
    description:
      "Protective water shoes that shield your feet from sharp rocks and hot sand. The quick-drying material and drainage holes keep your feet comfortable throughout the day. Available in multiple sizes for adults and children.",
    category: ["Swimming", "Snorkeling", "Scuba Diving"],
    location: "Colva Beach",
    available: 20,
  },
  {
    id: 13,
    title: "Inflatable Float",
    price: "399",
    rentPrice: 59,
    shopName: "FloatZone",
    images: [
      require("@/assets/Ecom/float1.png"),
      require("@/assets/Ecom/float1.png"),
      require("@/assets/Ecom/float1.png"),
    ],
    description:
      "Fun and colorful inflatable float perfect for relaxing on the water. The durable vinyl construction resists punctures while the comfortable design lets you lounge for hours. Includes a repair kit just in case.",
    category: ["Swimming", "Kids", "New Arrivals"],
    location: "Benaulim Beach",
    available: 8,
  },
  {
    id: 14,
    title: "Beach Game Set",
    price: "499",
    rentPrice: 79,
    shopName: "FunZone",
    images: [
      require("@/assets/Ecom/games1.png"),
      require("@/assets/Ecom/games1.png"),
      require("@/assets/Ecom/games1.png"),
    ],
    description:
      "Complete beach game set including volleyball, paddleball, frisbee, and spikeball. Everything you need for hours of entertainment on the sand. Comes in a convenient carrying bag for easy transportation.",
    category: ["Beach Games", "Kids"],
    location: "Cavelossim Beach",
    available: 5,
  },
  {
    id: 15,
    title: "Sand Toy Set",
    price: "299",
    rentPrice: 49,
    shopName: "KidZone",
    images: [
      require("@/assets/Ecom/sandtoys1.png"),
      require("@/assets/Ecom/sandtoys1.png"),
      require("@/assets/Ecom/sandtoys1.png"),
    ],
    description:
      "Colorful sand toy set including buckets, shovels, molds, and more. Perfect for keeping children entertained while building sandcastles and digging moats. Durable plastic construction stands up to beach play.",
    category: ["Kids", "Beach Games"],
    location: "Majorda Beach",
    available: 10,
  },
  {
    id: 16,
    title: "Kids Arm Floaties",
    price: "199",
    rentPrice: 29,
    shopName: "SafetyFirst",
    images: [
      require("@/assets/Ecom/floaties1.png"),
      require("@/assets/Ecom/floaties1.png"),
      require("@/assets/Ecom/floaties1.png"),
    ],
    description:
      "Brightly colored arm floaties designed specifically for children learning to swim. The double air chamber design provides reliable flotation while the safety valves prevent deflation. Available in multiple sizes for different age groups.",
    category: ["Kids", "Swimming", "Safety"],
    location: "Bogmalo Beach",
    available: 15,
  },
  {
    id: 17,
    title: "Kids Life Vest",
    price: "399",
    rentPrice: 59,
    shopName: "SafetyFirst",
    images: [
      require("@/assets/Ecom/kidsvest1.png"),
      require("@/assets/Ecom/kidsvest1.png"),
      require("@/assets/Ecom/kidsvest1.png"),
    ],
    description:
      "Coast Guard approved life vest designed specifically for children. Features adjustable straps and a crotch strap to prevent the vest from riding up. The bright colors ensure high visibility in the water for added safety.",
    category: ["Kids", "Swimming", "Safety"],
    location: "Varca Beach",
    available: 12,
  },
  {
    id: 18,
    title: "Splash Pool",
    price: "599",
    rentPrice: 99,
    shopName: "KidZone",
    images: [
      require("@/assets/Ecom/pool1.png"),
      require("@/assets/Ecom/pool1.png"),
      require("@/assets/Ecom/pool1.png"),
    ],
    description:
      "Inflatable splash pool perfect for young children to cool off safely. The soft bottom provides comfort while the low walls allow for easy supervision. Quick to set up and pack away when your beach day is done.",
    category: ["Kids", "Swimming", "New Arrivals"],
    location: "Betalbatim Beach",
    available: 4,
  },
  {
    id: 19,
    title: "Waterproof Phone Case",
    price: "299",
    rentPrice: 49,
    shopName: "BeachEssentials",
    images: [
      require("@/assets/Ecom/phonecase1.png"),
      require("@/assets/Ecom/phonecase1.png"),
      require("@/assets/Ecom/phonecase1.png"),
    ],
    description:
      "Fully submersible waterproof case that protects your phone while allowing full touchscreen functionality. Perfect for taking underwater photos or keeping your device safe during beach activities. Compatible with most smartphone models.",
    category: ["Storage", "Swimming", "Snorkeling"],
    location: "Agonda Beach",
    available: 20,
  },
  {
    id: 20,
    title: "Dry Bag",
    price: "399",
    rentPrice: 59,
    shopName: "BeachEssentials",
    images: [
      require("@/assets/Ecom/drybag1.png"),
      require("@/assets/Ecom/drybag1.png"),
      require("@/assets/Ecom/drybag1.png"),
    ],
    description:
      "Waterproof dry bag that keeps your valuables safe and dry during water activities. The roll-top closure ensures a watertight seal while the transparent window lets you see the contents. Available in multiple sizes to suit your needs.",
    category: ["Storage", "Swimming", "Paddling"],
    location: "Patnem Beach",
    available: 15,
  }
];